change log file ext

diff --git a/example/config/jobs/projects/hello-world/run b/example/config/jobs/projects/hello-world/run
--- a/example/config/jobs/projects/hello-world/run
+++ b/example/config/jobs/projects/hello-world/run
@@ -2,3 +2,4 @@
 set -euo pipefail
 
 echo "Hello World!"
+echo >&2 "Hello Error!"
